#ifndef KEY_CODES_H
#define KEY_CODES_H

/* Printable keys */
#define PANDEMONIUM_KEY_SPACE		  32
#define PANDEMONIUM_KEY_APOSTROPHE	  39 /* ' */
#define PANDEMONIUM_KEY_COMMA		  44 /* , */
#define PANDEMONIUM_KEY_MINUS		  45 /* - */
#define PANDEMONIUM_KEY_PERIOD		  46 /* . */
#define PANDEMONIUM_KEY_SLASH		  47 /* / */
#define PANDEMONIUM_KEY_0			  48
#define PANDEMONIUM_KEY_1			  49
#define PANDEMONIUM_KEY_2			  50
#define PANDEMONIUM_KEY_3			  51
#define PANDEMONIUM_KEY_4			  52
#define PANDEMONIUM_KEY_5			  53
#define PANDEMONIUM_KEY_6			  54
#define PANDEMONIUM_KEY_7			  55
#define PANDEMONIUM_KEY_8			  56
#define PANDEMONIUM_KEY_9			  57
#define PANDEMONIUM_KEY_SEMICOLON	  59 /* ; */
#define PANDEMONIUM_KEY_EQUAL		  61 /* = */
#define PANDEMONIUM_KEY_A			  65
#define PANDEMONIUM_KEY_B			  66
#define PANDEMONIUM_KEY_C			  67
#define PANDEMONIUM_KEY_D			  68
#define PANDEMONIUM_KEY_E			  69
#define PANDEMONIUM_KEY_F			  70
#define PANDEMONIUM_KEY_G			  71
#define PANDEMONIUM_KEY_H			  72
#define PANDEMONIUM_KEY_I			  73
#define PANDEMONIUM_KEY_J			  74
#define PANDEMONIUM_KEY_K			  75
#define PANDEMONIUM_KEY_L			  76
#define PANDEMONIUM_KEY_M			  77
#define PANDEMONIUM_KEY_N			  78
#define PANDEMONIUM_KEY_O			  79
#define PANDEMONIUM_KEY_P			  80
#define PANDEMONIUM_KEY_Q			  81
#define PANDEMONIUM_KEY_R			  82
#define PANDEMONIUM_KEY_S			  83
#define PANDEMONIUM_KEY_T			  84
#define PANDEMONIUM_KEY_U			  85
#define PANDEMONIUM_KEY_V			  86
#define PANDEMONIUM_KEY_W			  87
#define PANDEMONIUM_KEY_X			  88
#define PANDEMONIUM_KEY_Y			  89
#define PANDEMONIUM_KEY_Z			  90
#define PANDEMONIUM_KEY_LEFT_BRACKET  91  /* [ */
#define PANDEMONIUM_KEY_BACKSLASH	  92  /* \ */
#define PANDEMONIUM_KEY_RIGHT_BRACKET 93  /* ] */
#define PANDEMONIUM_KEY_GRAVE_ACCENT  96  /* ` */
#define PANDEMONIUM_KEY_WORLD_1		  161 /* non-US #1 */
#define PANDEMONIUM_KEY_WORLD_2		  162 /* non-US #2 */

/* Function keys */
#define PANDEMONIUM_KEY_ESCAPE		  256
#define PANDEMONIUM_KEY_ENTER		  257
#define PANDEMONIUM_KEY_TAB			  258
#define PANDEMONIUM_KEY_BACKSPACE	  259
#define PANDEMONIUM_KEY_INSERT		  260
#define PANDEMONIUM_KEY_DELETE		  261
#define PANDEMONIUM_KEY_RIGHT		  262
#define PANDEMONIUM_KEY_LEFT		  263
#define PANDEMONIUM_KEY_DOWN		  264
#define PANDEMONIUM_KEY_UP			  265
#define PANDEMONIUM_KEY_PAGE_UP		  266
#define PANDEMONIUM_KEY_PAGE_DOWN	  267
#define PANDEMONIUM_KEY_HOME		  268
#define PANDEMONIUM_KEY_END			  269
#define PANDEMONIUM_KEY_CAPS_LOCK	  280
#define PANDEMONIUM_KEY_SCROLL_LOCK	  281
#define PANDEMONIUM_KEY_NUM_LOCK	  282
#define PANDEMONIUM_KEY_PRINT_SCREEN  283
#define PANDEMONIUM_KEY_PAUSE		  284
#define PANDEMONIUM_KEY_F1			  290
#define PANDEMONIUM_KEY_F2			  291
#define PANDEMONIUM_KEY_F3			  292
#define PANDEMONIUM_KEY_F4			  293
#define PANDEMONIUM_KEY_F5			  294
#define PANDEMONIUM_KEY_F6			  295
#define PANDEMONIUM_KEY_F7			  296
#define PANDEMONIUM_KEY_F8			  297
#define PANDEMONIUM_KEY_F9			  298
#define PANDEMONIUM_KEY_F10			  299
#define PANDEMONIUM_KEY_F11			  300
#define PANDEMONIUM_KEY_F12			  301
#define PANDEMONIUM_KEY_F13			  302
#define PANDEMONIUM_KEY_F14			  303
#define PANDEMONIUM_KEY_F15			  304
#define PANDEMONIUM_KEY_F16			  305
#define PANDEMONIUM_KEY_F17			  306
#define PANDEMONIUM_KEY_F18			  307
#define PANDEMONIUM_KEY_F19			  308
#define PANDEMONIUM_KEY_F20			  309
#define PANDEMONIUM_KEY_F21			  310
#define PANDEMONIUM_KEY_F22			  311
#define PANDEMONIUM_KEY_F23			  312
#define PANDEMONIUM_KEY_F24			  313
#define PANDEMONIUM_KEY_F25			  314
#define PANDEMONIUM_KEY_KP_0		  320
#define PANDEMONIUM_KEY_KP_1		  321
#define PANDEMONIUM_KEY_KP_2		  322
#define PANDEMONIUM_KEY_KP_3		  323
#define PANDEMONIUM_KEY_KP_4		  324
#define PANDEMONIUM_KEY_KP_5		  325
#define PANDEMONIUM_KEY_KP_6		  326
#define PANDEMONIUM_KEY_KP_7		  327
#define PANDEMONIUM_KEY_KP_8		  328
#define PANDEMONIUM_KEY_KP_9		  329
#define PANDEMONIUM_KEY_KP_DECIMAL	  330
#define PANDEMONIUM_KEY_KP_DIVIDE	  331
#define PANDEMONIUM_KEY_KP_MULTIPLY	  332
#define PANDEMONIUM_KEY_KP_SUBTRACT	  333
#define PANDEMONIUM_KEY_KP_ADD		  334
#define PANDEMONIUM_KEY_KP_ENTER	  335
#define PANDEMONIUM_KEY_KP_EQUAL	  336
#define PANDEMONIUM_KEY_LEFT_SHIFT	  340
#define PANDEMONIUM_KEY_LEFT_CONTROL  341
#define PANDEMONIUM_KEY_LEFT_ALT	  342
#define PANDEMONIUM_KEY_LEFT_SUPER	  343
#define PANDEMONIUM_KEY_RIGHT_SHIFT	  344
#define PANDEMONIUM_KEY_RIGHT_CONTROL 345
#define PANDEMONIUM_KEY_RIGHT_ALT	  346
#define PANDEMONIUM_KEY_RIGHT_SUPER	  347
#define PANDEMONIUM_KEY_MENU		  348

#endif /* KEY_CODES_H */